networks:
  repid-crm:
    driver: bridge

volumes:
  pg_data: null
  
services:
  nginx:
    networks:
      - repid-crm
    ports:
      - ${PORT:-8001}:80
    volumes:
      - ./resources/layout/nginx.conf:/etc/nginx/nginx.conf
      - ./resources/:/usr/share/nginx/html/resources/
    build:
      context: .
      dockerfile: ./docker/Dockerfile.nginx
    depends_on:
      - web
    restart: always
    
  web:
    networks:
      - repid-crm
    build:
      context: .
      dockerfile: ./docker/Dockerfile.web
    command: ${COMMAND:-sh ./resources/scripts/entrypoint.sh}
    environment:
      - PYTHONPYCACHEPREFIX=/var/cache/pycache
    volumes:
      - './:/code'
    depends_on:
      - db
    restart: always

  db:
    image: postgres:17
    networks:
      - repid-crm
    environment:
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: always